@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sat May 07 13:04:18 -0300 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto eb4a2876d5444994a8916a26a057d7b1 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Tb_Anti_Bouncing_behav xil_defaultlib.Tb_Anti_Bouncing -log elaborate.log"
call xelab  -wto eb4a2876d5444994a8916a26a057d7b1 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Tb_Anti_Bouncing_behav xil_defaultlib.Tb_Anti_Bouncing -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
